name: run-phpunit

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install NPM && Composer Dependencies
        run:
          npm install
          composer install

      - name: Start WordPress Environment
        run: npm run start-env

      - name: Run PHPUnit Tests
        run: npm run test-php

      - name: Stop WordPress Environment
        run: npm run stop-env

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer:v2

      - name: Install Composer Dependencies
        run: composer install --no-progress

      - name: Run PHP CodeSniffer
        run: ./vendor/bin/phpcs